<a href="https://colab.research.google.com/github/crazat/crazat.githurb.io/blob/main/data_leakage_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- 신용 위험 이진분류 데이터셋 다운로드 받아 구글드라이브에 올리기
    - 학습세트
        - https://drive.google.com/file/d/1YdE8tDjXmRaoXfxdwnwJzSDXhcI--ep3/view?usp=sharing
        - https://drive.google.com/file/d/1FIUBfDmoH9ibWvfsVqcb2DXvm_Hv7OJr/view?usp=sharing
    - 평가세트
        - https://drive.google.com/file/d/16GjeCJS5q-uhp2b5ElUXS0sk88x8gUnK/view?usp=sharing
        - https://drive.google.com/file/d/1Rv1z6Y5S0fvJ04hlrxjuJXUNnyU70ywg/view?usp=sharing

- 구글 드라이브 연결

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

- 데이터 경로 변수

In [ ]:
DATA_PATH = "/content/drive/MyDrive/머신러닝/data/"
DATA_PATH

'/content/drive/MyDrive/머신러닝/data/'

- 데이터 불러오기

In [ ]:
import pandas as pd
import numpy as np

train_customer = pd.read_csv(f"{DATA_PATH}credit_customer_train.csv") # 학습데이터(고객 개인정보)
train_payment = pd.read_csv(f"{DATA_PATH}credit_payment_train.csv") # 학습데이터(고객의 카드값 변제 내역)

test_customer = pd.read_csv(f"{DATA_PATH}credit_customer_test.csv") # 테스트데이터(고객 개인정보)
test_payment = pd.read_csv(f"{DATA_PATH}credit_payment_test.csv") # 테스트데이터(고객의 카드값 변제 내역)
train_customer.shape , train_payment.shape, test_customer.shape , test_payment.shape

((787, 13), (5693, 12), (338, 12), (2557, 12))

- 고객 개인정보 데이터
    - 컬럼명이 비식별화 되어 있음

In [ ]:
train_customer.head()

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,수치4,수치5,신용위험도
0,58996294,7,1,2,11,5,3,1239.5,110000.0,80,60064,1.000000,0
1,54988879,4,3,2,8,-1,5,1223.0,68000.0,112,340014,187.082869,0
2,58984937,5,1,2,15,-1,4,1296.5,130000.0,86,60018,158.113883,0
3,58987530,5,1,2,15,5,3,1304.0,146000.0,90,350008,1.000000,0
4,59003965,4,2,2,8,9,4,0.0,76000.0,113,60091,158.407702,0

- 고객의 카드값 변제 내역

In [ ]:
train_payment.head()

/usr/local/lib/python3.11/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,고객ID,연체횟수유형1,연체횟수유형2,연체횟수유형3,총연체일수,정상결제횟수,카드코드,카드한도,계정업데이트날짜,카드현재잔액,카드최고잔액,최근지불날짜
0,58987402,0,0,0,0,1,10,16500.0,04/12/2016,0.0,NaN,NaN
1,58995151,0,0,0,0,1,5,NaN,04/12/2016,588720.0,491100.0,NaN
2,58997200,0,0,0,0,2,5,NaN,04/12/2016,840000.0,700500.0,22/04/2016
3,54987763,0,0,0,0,2,10,NaN,03/12/2016,15147.6,NaN,26/04/2016
4,58994429,0,0,0,0,2,10,16500.0,02/12/2016,3252.0,3210.0,NaN

- 고객별 카드값 변제 내역이 있음

In [ ]:
train_payment.sort_values(by="고객ID").head(50)

,고객ID,연체횟수유형1,연체횟수유형2,연체횟수유형3,총연체일수,정상결제횟수,카드코드,카드한도,계정업데이트날짜,카드현재잔액,카드최고잔액,최근지불날짜
5389,54982353,1,2,3,562,13,10,NaN,22/04/2005,0.0,5831.0,07/10/2005
4970,54982353,0,0,0,0,5,10,NaN,12/03/2007,0.0,NaN,NaN
1848,54982353,0,0,0,0,1,10,55000.0,27/08/2014,0.0,2068.0,12/06/2014
4971,54982353,0,0,0,0,12,10,NaN,12/03/2007,120381.6,546657.0,21/05/2011
5540,54982353,0,0,0,0,4,10,NaN,17/09/2003,0.0,4458.0,28/03/2006
5580,54982353,0,0,0,0,35,10,5500.0,05/01/2003,0.0,4043.0,25/11/2003
5059,54982353,0,0,0,0,1,10,NaN,21/11/2006,0.0,NaN,NaN
5534,54982353,0,0,0,0,34,10,NaN,17/10/2003,0.0,5610.0,28/05/2005
2662,54982353,1,0,0,1,31,10,550000.0,03/09/2013,326684.4,609683.0,18/12/2015
5623,54982353,0,0,0,0,11,2,NaN,21/02/2001,0.0,248874.0,22/06/2007
4257,54982353,0,0,35,31500,0,10,12100.0,27/12/2008,12142.8,10619.0,14/07/2009
3724,54982353,0,0,0,0,19,10,NaN,16/07/2011,31677.6,204037.0,14/12/2015
5418,54982353,0,0,0,0,1,1,NaN,16/02/2005,0.0,700500.0,18/01/2008
5282,54982353,0,0,0,0,1,10,NaN,08/01/2006,0.0,1622.0,NaN
4969,54982353,0,0,0,0,26,10,660000.0,12/03/2007,252998.4,775030.0,23/12/2015
5672,54982353,0,0,0,0,0,10,NaN,18/12/1994,13909.2,NaN,NaN
5327,54982353,0,0,0,0,0,10,NaN,30/09/2005,0.0,NaN,NaN
5664,54982353,1,0,0,15,35,10,275000.0,21/04/1997,-1197.6,333140.0,21/07/2015
5627,54982356,0,0,0,0,0,6,NaN,14/01/2001,0.0,18000.0,NaN
5628,54982356,0,0,0,0,10,6,NaN,14/01/2001,0.0,16000.0,NaN
5214,54982356,0,0,0,0,36,10,NaN,30/03/2006,15938.4,28740.0,26/11/2015
5160,54982356,0,0,0,0,1,27,NaN,19/06/2006,0.0,600500.0,26/10/2010
5161,54982356,0,0,0,0,16,27,NaN,19/06/2006,0.0,600500.0,NaN
5653,54982356,0,0,0,0,36,10,330000.0,17/06/1998,6.0,81139.0,10/05/2013
5651,54982356,0,0,0,0,18,12,NaN,02/10/1998,0.0,31666.0,28/06/2006
3520,54982387,1,0,0,1,35,10,68200.0,25/02/2012,15694.8,14537.0,26/03/2016
1644,54982387,0,0,0,0,11,6,NaN,11/11/2014,0.0,29940.0,20/09/2015
1645,54982387,0,0,0,0,15,6,NaN,11/11/2014,0.0,23291.0,14/02/2016
1646,54982387,0,0,0,0,15,6,NaN,11/11/2014,0.0,69273.0,02/12/2016
1748,54982387,0,0,0,0,1,6,NaN,09/10/2014,0.0,106087.0,24/05/2015
5117,54982387,0,0,0,0,21,10,13200.0,30/08/2006,0.0,51056.0,10/08/2011
3376,54982387,2,0,0,11,30,10,330000.0,03/07/2012,3481.2,98269.0,18/05/2016
1583,54982387,0,0,0,0,26,1,NaN,04/12/2014,917833.2,1200500.0,25/03/2016
3893,54982387,0,0,0,0,28,1,NaN,10/09/2010,0.0,500500.0,23/12/2012
5539,54982387,0,0,0,0,36,10,26400.0,17/09/2003,5268.0,27017.0,22/03/2016
2714,54982387,0,0,0,0,28,1,NaN,10/08/2013,349729.2,500500.0,03/04/2016
2187,54982463,0,0,0,0,15,5,NaN,07/04/2014,79780.8,100500.0,24/08/2015
3548,54982463,0,0,0,0,19,13,NaN,27/01/2012,0.0,56500.0,26/07/2013
1795,54982530,0,0,0,0,12,10,134200.0,16/09/2014,673.2,24117.0,17/07/2015
1335,54982530,0,0,0,0,7,10,55000.0,21/02/2015,0.0,3806.0,21/08/2015
2484,54982530,0,0,0,0,25,10,NaN,04/12/2013,4371.6,14955.0,18/08/2015
1771,54982530,0,0,0,0,12,10,NaN,28/09/2014,0.0,8273.0,16/09/2015
4174,54982665,0,0,0,0,1,5,NaN,30/03/2009,0.0,150500.0,NaN
1404,54982665,0,0,0,0,9,10,60500.0,31/01/2015,6657.6,18934.0,19/09/2015
4145,54982665,0,0,0,0,18,10,NaN,28/04/2009,153792.0,149387.0,10/08/2015
4915,54982665,0,2,26,11906,6,10,NaN,17/05/2007,0.0,46371.0,12/07/2013
3115,54982697,0,0,0,0,28,10,NaN,07/01/2013,17145.6,20441.0,20/09/2015
1662,54982697,0,0,0,0,17,10,135300.0,06/11/2014,360.0,48811.0,17/10/2015
4784,54982721,0,0,34,30600,1,13,NaN,09/09/2007,0.0,54500.0,06/06/2014
5081,54982721,0,0,0,0,36,10,NaN,24/10/2006,0.0,32565.0,14/12/2008

- train_customer에서 정답 제외하고 복사하기

In [ ]:
train_ft = train_customer.iloc[:,:-1].copy()
test_ft = test_customer.copy() # 테스트는 정답 컬럼이 없음
train_ft.shape , test_ft.shape

((787, 12), (338, 12))

# Data leakage
- 머신러닝에서 Data leakage는 예측 시 사용할 수 없는 정보가 모델의 학습및 평가에서 사용되는 것을 말한다.
- Data leakage 문제가 있으면 모델이 과대평가 되고 모델의 일반화 가능성이 보장되지 않는다.
- Data leakage 문제
    - 실제 서비스 환경에서 예측할 때 사용할 수 없는 피처를 수집하여 학습 데이터와 테스트 데이터에서 사용하여 모델 학습 및 성능을 평가 하는 경우
    - 테스트 데이터의 정보를 모델의 학습및 평가에 사용하는 경우

# 테스트 데이터의 정보를 모델의 학습및 평가에 사용하는 경우
- 우리가 모르는 데이터라고 가정한 테스트 데이터의 정보를 모델의 학습에 사용할 경우 Data leakage 이다.

## 다른 샘플들의 통계치를 이용하여 피처를 생성하는 경우
- "범주4" 컬럼 별로 "수치1" 컬럼의 평균값을 피처로 추가하기

In [ ]:
agg_dict = {"수치1":"mean"}
train_agg = train_customer.groupby("범주4").agg(agg_dict).add_suffix("_mean").reset_index()
train_agg

   범주4     수치1_mean
0    3  1378.250000
1    4  1211.750000
2    5   911.333333
3    6  1217.000000
4    8  1034.854086
5    9  1386.500000
6   11  1143.617825
7   12  1018.388889
8   15  1148.430556
9   16     0.000000

- merge

In [ ]:
train_ft = pd.merge(train_ft,train_agg,how="left",on="범주4")
train_ft.head()

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,수치4,수치5,수치1_mean
0,58996294,7,1,2,11,5,3,1239.5,110000.0,80,60064,1.000000,1143.617825
1,54988879,4,3,2,8,-1,5,1223.0,68000.0,112,340014,187.082869,1034.854086
2,58984937,5,1,2,15,-1,4,1296.5,130000.0,86,60018,158.113883,1148.430556
3,58987530,5,1,2,15,5,3,1304.0,146000.0,90,350008,1.000000,1148.430556
4,59003965,4,2,2,8,9,4,0.0,76000.0,113,60091,158.407702,1034.854086

### Data leakage 발생 예시
- 테스트 데이터를 집계하여 피처를 추가할 경우 Data leakage 이다.

In [ ]:
test_agg = test_customer.groupby("범주4").agg(agg_dict).add_suffix("_mean").reset_index()
pd.merge(test_ft,test_agg,how="left",on="범주4")

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,수치4,수치5,수치1_mean
0,58991594,7,3,1,11,5,5,1365.5,152000.0,84,60006,173.205081,1149.011194
1,54983822,5,3,2,15,5,4,0.0,94000.0,113,60057,193.636257,1106.462025
2,54984131,5,3,2,15,5,5,1244.0,57000.0,95,151300,173.205081,1106.462025
3,58994981,7,2,2,11,5,3,0.0,72000.0,109,60019,169.484513,1149.011194
4,59004856,4,2,2,8,5,3,0.0,99000.0,90,60036,188.066478,1127.271186
...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,58992009,7,3,2,11,9,3,1290.5,273000.0,113,60063,223.606798,1149.011194
334,58993131,7,2,2,11,5,5,0.0,120000.0,101,72000,265.339405,1149.011194
335,58993847,7,3,2,11,9,4,1262.0,172000.0,112,72000,262.110664,1149.011194
336,58995703,7,3,2,11,9,5,0.0,75000.0,100,450018,353.553391,1149.011194
337,54989304,4,3,2,8,9,5,1238.0,125000.0,85,60002,1.000000,1127.271186

### Data leakage 해결 방안
- 학습데이터에서 집계한 train_agg 변수로 merge 해야한다.

In [ ]:
test_ft = pd.merge(test_ft,train_agg,how="left",on="범주4")
test_ft

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,수치4,수치5,수치1_mean
0,58991594,7,3,1,11,5,5,1365.5,152000.0,84,60006,173.205081,1143.617825
1,54983822,5,3,2,15,5,4,0.0,94000.0,113,60057,193.636257,1148.430556
2,54984131,5,3,2,15,5,5,1244.0,57000.0,95,151300,173.205081,1148.430556
3,58994981,7,2,2,11,5,3,0.0,72000.0,109,60019,169.484513,1143.617825
4,59004856,4,2,2,8,5,3,0.0,99000.0,90,60036,188.066478,1034.854086
...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,58992009,7,3,2,11,9,3,1290.5,273000.0,113,60063,223.606798,1143.617825
334,58993131,7,2,2,11,5,5,0.0,120000.0,101,72000,265.339405,1143.617825
335,58993847,7,3,2,11,9,4,1262.0,172000.0,112,72000,262.110664,1143.617825
336,58995703,7,3,2,11,9,5,0.0,75000.0,100,450018,353.553391,1143.617825
337,54989304,4,3,2,8,9,5,1238.0,125000.0,85,60002,1.000000,1034.854086

### Data leakage가 아닌 경우
- 변제내역 데이터에서 고객별 연체횟수 합계 피처 생성 후 merge

In [ ]:
# 학습데이터
agg_dict = {"연체횟수유형1":"sum"}
tmp = train_payment.groupby("고객ID").agg(agg_dict).add_suffix("_sum").reset_index()
pd.merge(train_ft,tmp,how="left",on="고객ID")

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,수치4,수치5,수치1_mean,연체횟수유형1_sum
0,58996294,7,1,2,11,5,3,1239.5,110000.0,80,60064,1.000000,1143.617825,0
1,54988879,4,3,2,8,-1,5,1223.0,68000.0,112,340014,187.082869,1034.854086,0
2,58984937,5,1,2,15,-1,4,1296.5,130000.0,86,60018,158.113883,1148.430556,0
3,58987530,5,1,2,15,5,3,1304.0,146000.0,90,350008,1.000000,1148.430556,1
4,59003965,4,2,2,8,9,4,0.0,76000.0,113,60091,158.407702,1034.854086,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782,58994117,7,1,2,11,5,3,1323.5,122000.0,86,151300,1.000000,1143.617825,1
783,58995289,7,2,2,11,5,4,0.0,50000.0,113,450080,167.564913,1143.617825,1
784,58996500,7,1,2,11,9,5,1328.0,189000.0,85,60019,1.000000,1143.617825,0
785,59001833,4,3,2,8,9,4,1250.0,95000.0,111,60047,1.000000,1034.854086,0
786,59005917,4,1,2,8,-1,5,1266.5,104000.0,92,60036,1.000000,1034.854086,0

- 하나의 샘플이 여러 개의 행으로 구성된 데이터 집계하여 피쳐생성할 때 테스트데이터에도 동일한 방식으로 집계하는 것은 Data leakage가 아니다.

In [ ]:
# 테스트 데이터
tmp = test_payment.groupby("고객ID").agg(agg_dict).add_suffix("_sum").reset_index()
pd.merge(test_ft,tmp,how="left",on="고객ID")

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,수치4,수치5,수치1_mean,연체횟수유형1_sum
0,58991594,7,3,1,11,5,5,1365.5,152000.0,84,60006,173.205081,1143.617825,0
1,54983822,5,3,2,15,5,4,0.0,94000.0,113,60057,193.636257,1148.430556,1
2,54984131,5,3,2,15,5,5,1244.0,57000.0,95,151300,173.205081,1148.430556,0
3,58994981,7,2,2,11,5,3,0.0,72000.0,109,60019,169.484513,1143.617825,0
4,59004856,4,2,2,8,5,3,0.0,99000.0,90,60036,188.066478,1034.854086,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,58992009,7,3,2,11,9,3,1290.5,273000.0,113,60063,223.606798,1143.617825,1
334,58993131,7,2,2,11,5,5,0.0,120000.0,101,72000,265.339405,1143.617825,8
335,58993847,7,3,2,11,9,4,1262.0,172000.0,112,72000,262.110664,1143.617825,5
336,58995703,7,3,2,11,9,5,0.0,75000.0,100,450018,353.553391,1143.617825,28
337,54989304,4,3,2,8,9,5,1238.0,125000.0,85,60002,1.000000,1034.854086,1

- 다른 샘플을 활용한 것이 아니기 때문

In [ ]:
test_payment.groupby("고객ID").apply(lambda x : x.set_index("고객ID")).head(50)

<ipython-input-14-136ec5bc777c>:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_payment.groupby("고객ID").apply(lambda x : x.set_index("고객ID")).head(50)

                   연체횟수유형1  연체횟수유형2  연체횟수유형3  총연체일수  정상결제횟수  카드코드      카드한도  \
고객ID     고객ID
54982549 54982549        0        0        0      0       4    17       NaN
         54982549        0        0        0      0      11     6       NaN
         54982549        0        0        0      0      11     6       NaN
         54982549        0        0        0      0      33     1       NaN
         54982549        0        0        0      0      30     2       NaN
         54982549        0        0        0      0      36     5       NaN
         54982549        0        0        0      0      27    17       NaN
         54982549        6        2        0    330       5    17       NaN
         54982549        0        0        0      0      27    17       NaN
         54982549        0        0        0      0      27    17       NaN
54982579 54982579        0        0        0      0      19     2       NaN
         54982579        0        0        0      0      16    10       NaN
         54982579        0        0        0      0      34    10  410300.0
         54982579        0        0        0      0      36    10       NaN
         54982579        0        0        0      0       2    10       NaN
         54982579        0        0        0      0      35    10  275000.0
         54982579        0        0        0      0      36     2       NaN
         54982579        1        0        0     17       6    10       NaN
         54982579        0        0        0      0      33    10       NaN
         54982579        0        0        0      0      33     1       NaN
         54982579        0        0        0      0      23    10       NaN
         54982579        0        0        0      0       1    10   68200.0
         54982579        0        0        0      0       0    10       NaN
         54982579        0        0        0      0       5    10       NaN
         54982579        0        0        0      0       0    10       NaN
         54982579        0        0        0      0       1    10       NaN
         54982579        0        0        0      0       1    10       NaN
         54982579        0        0        0      0      33    10       NaN
         54982579        0        0        0      0       7    10       NaN
         54982579        0        0        0      0       1     1       NaN
         54982579        0        0        0      0       1    10   25300.0
         54982579        0        0        0      0       0     1       NaN
54982727 54982727        0        0        0      0       1    10   70400.0
         54982727        0        0        0      0       8    10       NaN
         54982727        0        0        0      0       2     6       NaN
         54982727        0        0        0      0       2     5       NaN
         54982727        0        0        0      0       3     0       NaN
         54982727        0        0        0      0       3     0       NaN
         54982727        0        0        0      0       1     5       NaN
         54982727        0        0        0      0       6    10       NaN
         54982727        0        0        0      0       7     7       NaN
         54982727        2        0        0     23       7     7       NaN
         54982727        1        0        0     21       8     7       NaN
         54982727        0        0        0      0       1     7       NaN
         54982727        9        0        2    575       9     5       NaN
         54982727        0        0        0      0      36    10   35200.0
         54982727        0        1        9   1956       6    10       NaN
         54982727        0        0        0      0       1    10   33000.0
         54982727        0       11       14   2420      11     1       NaN
         54982727        1        0        0      9      12     6       NaN

                     계정업데이트날짜     카드현재잔액     카드최고잔액      최근지불날짜
고객ID     고객ID
54982549 54982549  18/06/2015   622860.0   500500.0  09/09/2015
         54982549  12/01/2014        0.0    35000.0  24/08/2015
         54982549  12/01/2014        0.0    39500.0  13/05/2015
         54982549  15/01/2013   119428.8  1100500.0  09/03/2015
         54982549  16/02/2011  3358315.2  3000500.0  24/07/2013
         54982549  16/01/2011        0.0   350500.0  27/01/2014
         54982549  30/05/2010        0.0   500500.0  22/02/2011
         54982549  12/04/2010        0.0   330500.0  15/02/2014
         54982549  09/07/2009        0.0   600500.0  22/02/2011
         54982549  01/02/2008        0.0   260500.0  12/06/2010
54982579 54982579  04/05/2014    72666.0    79462.0  17/09/2015
         54982579  19/01/2014     1417.2    22889.0  08/08/2015
         54982579  20/09/2012    11510.4    12214.0  20/09/2015
         54982579  30/04/2012        0.0    91631.0  07/02/2015
         54982579  21/06/2010        0.0     1052.0         NaN
         54982579  16/05/2010        0.0   250500.0  19/08/2014
         54982579  26/10/2008  1768387.2  2057500.0  17/09/2015
         54982579  16/09/2008     6264.0        NaN         NaN
         54982579  16/09/2008    41757.6        NaN  16/09/2015
         54982579  20/03/2008        0.0   400500.0  25/02/2011
         54982579  15/02/2008        0.0        NaN         NaN
         54982579  05/05/2007        0.0        NaN         NaN
         54982579  15/02/2007        0.0        NaN         NaN
         54982579  29/01/2007        0.0        NaN         NaN
         54982579  06/12/2006        0.0      609.0         NaN
         54982579  19/07/2006        0.0        NaN         NaN
         54982579  06/04/2006        0.0     2671.0  27/10/2006
         54982579  21/01/2006        0.0        NaN         NaN
         54982579  17/12/2005        0.0     5226.0  13/02/2006
         54982579  29/12/2004        0.0   270500.0  16/01/2006
         54982579  12/04/2004        0.0    15258.0  02/10/2008
         54982579  11/09/2001        0.0    86500.0         NaN
54982727 54982727  30/09/2015     4044.0     3869.0         NaN
         54982727  01/09/2015    30358.8    29407.0  21/08/2015
         54982727  09/08/2015    17270.4    21060.0         NaN
         54982727  26/04/2015   444398.4   375400.0         NaN
         54982727  26/04/2015   437126.4   375400.0         NaN
         54982727  22/04/2015   118870.8   100500.0  23/04/2015
         54982727  22/04/2015        0.0   100500.0         NaN
         54982727  24/03/2015     9772.8        NaN  09/09/2015
         54982727  21/12/2014        0.0   216500.0  17/08/2015
         54982727  01/10/2014   107917.2    90500.0  26/10/2014
         54982727  31/12/2013   259767.6   217111.0  26/10/2014
         54982727  31/12/2013        0.0   217111.0  31/12/2013
         54982727  06/09/2009        0.0   167500.0  07/11/2012
         54982727  09/08/2009        0.0    48300.0  02/05/2012
         54982727  15/06/2009        0.0    68521.0  19/03/2011
         54982727  31/12/2008        0.0    32934.0         NaN
         54982727  26/12/2008        0.0   234372.0  14/12/2014
         54982727  04/07/2007        0.0    11490.0  28/07/2008

- 변제 내역 데이터에서 피처 추출해서 merge

In [ ]:
agg_dict = {
    # key: 집계대상컬럼
    # value: 변경할 컬럼명과 집계문자열/함수를 튜플에 담고 리스트에 넣으면 된다.
    "연체횟수유형1": [
        ("연체횟수유형1_sum","sum"),
        ("변제횟수","count") # 카운팅하여 변제횟수 피쳐 생성
    ],
    "연체횟수유형2": [
        ("연체횟수유형2_sum","sum")
    ],
    "연체횟수유형3": [
        ("연체횟수유형3_sum","sum")
    ],
    "총연체일수": [
        ("총연체일수_sum","sum")
    ],
    "정상결제횟수": [
        ("정상결제횟수_sum","sum"),
        ("정상결제횟수_mean","mean"),
        ("정상결제횟수_std","std"),
    ],
    "카드코드": [
        ("카드코드_nunique","nunique"),
    ],
    "카드한도": [
        ("카드한도_mean","mean"),
        ("카드한도_std","std"),
    ],
    "카드현재잔액": [
        ("카드현재잔액_mean","mean"),
        ("카드현재잔액_std","std"),
    ],
    "카드최고잔액": [
        ("카드최고잔액_mean","mean"),
        ("카드최고잔액_std","std"),
    ],
}
tmp = train_payment.groupby("고객ID").agg(agg_dict)
tmp # 멀티 컬럼이 생성됨

             연체횟수유형1          연체횟수유형2     연체횟수유형3     총연체일수     정상결제횟수  \
         연체횟수유형1_sum 변제횟수 연체횟수유형2_sum 연체횟수유형3_sum 총연체일수_sum 정상결제횟수_sum
고객ID
54982353           3   18           2          38     32078        229
54982356           0    7           0           0         0        117
54982387           3   11           0           0        12        246
54982463           0    2           0           0         0         34
54982530           0    4           0           0         0         56
...              ...  ...         ...         ...       ...        ...
59005917           0    2           0           0         0         17
59005995           0    3           0           0         0         49
59006193           0    8           0           0         0        106
59006219           1    3           0           0        28         81
59006239           0    3           0           0         0         32

                                        카드코드      카드한도                 \
         정상결제횟수_mean 정상결제횟수_std 카드코드_nunique 카드한도_mean       카드한도_std
고객ID
54982353   12.722222  13.654586            3  259600.0  287253.790227
54982356   16.714286  14.817943            4  330000.0            NaN
54982387   22.363636  10.846868            3  109450.0  148890.597420
54982463   17.000000   2.828427            2       NaN            NaN
54982530   14.000000   7.702813            1   94600.0   56002.857070
...              ...        ...          ...       ...            ...
59005917    8.500000   6.363961            1  105600.0            NaN
59005995   16.333333  11.590226            2   35200.0   10889.444430
59006193   13.250000  11.360961            2  105160.0   31725.037431
59006219   27.000000  14.730920            2   33000.0            NaN
59006239   10.666667   9.073772            2   15400.0            NaN

                 카드현재잔액                        카드최고잔액
            카드현재잔액_mean     카드현재잔액_std    카드최고잔액_mean     카드최고잔액_std
고객ID
54982353   42033.133333   95414.365020  246583.714286  294232.061830
54982356    2277.771429    6023.771407  196649.285714  276735.785384
54982387  117455.127273  285177.439067  238270.000000  367205.535992
54982463   39890.400000   56413.544688   78500.000000   31112.698372
54982530    1261.200000    2097.743473   12787.750000    8833.717201
...                 ...            ...            ...            ...
59005917    7432.200000    6548.091636   18773.500000    5701.401977
59005995   57099.600000   51136.985727  105173.666667  126020.724606
59006193   13651.350000   30201.805753   50328.625000   24775.431551
59006219  179909.200000  301856.158793  189248.666667  269777.221797
59006239     830.800000    1438.987811   16780.333333    3734.477250

[787 rows x 15 columns]

In [ ]:
# 멀티컬럼 제거하고 고객ID 컬럼데이터로 만들기
tmp.columns = tmp.columns.droplevel() # 기본으로 0레벨 컬럼 제거해서 반환
tmp = tmp.reset_index()  # 고객ID 컬럼데이터로 만들기
tmp

,고객ID,연체횟수유형1_sum,변제횟수,연체횟수유형2_sum,연체횟수유형3_sum,총연체일수_sum,정상결제횟수_sum,정상결제횟수_mean,정상결제횟수_std,카드코드_nunique,카드한도_mean,카드한도_std,카드현재잔액_mean,카드현재잔액_std,카드최고잔액_mean,카드최고잔액_std
0,54982353,3,18,2,38,32078,229,12.722222,13.654586,3,259600.0,287253.790227,42033.133333,95414.365020,246583.714286,294232.061830
1,54982356,0,7,0,0,0,117,16.714286,14.817943,4,330000.0,NaN,2277.771429,6023.771407,196649.285714,276735.785384
2,54982387,3,11,0,0,12,246,22.363636,10.846868,3,109450.0,148890.597420,117455.127273,285177.439067,238270.000000,367205.535992
3,54982463,0,2,0,0,0,34,17.000000,2.828427,2,NaN,NaN,39890.400000,56413.544688,78500.000000,31112.698372
4,54982530,0,4,0,0,0,56,14.000000,7.702813,1,94600.0,56002.857070,1261.200000,2097.743473,12787.750000,8833.717201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
782,59005917,0,2,0,0,0,17,8.500000,6.363961,1,105600.0,NaN,7432.200000,6548.091636,18773.500000,5701.401977
783,59005995,0,3,0,0,0,49,16.333333,11.590226,2,35200.0,10889.444430,57099.600000,51136.985727,105173.666667,126020.724606
784,59006193,0,8,0,0,0,106,13.250000,11.360961,2,105160.0,31725.037431,13651.350000,30201.805753,50328.625000,24775.431551
785,59006219,1,3,0,0,28,81,27.000000,14.730920,2,33000.0,NaN,179909.200000,301856.158793,189248.666667,269777.221797
786,59006239,0,3,0,0,0,32,10.666667,9.073772,2,15400.0,NaN,830.800000,1438.987811,16780.333333,3734.477250

In [ ]:
# 추출한 피쳐 merge
train_ft = pd.merge(train_ft,tmp,how="left",on="고객ID")
train_ft.head()

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,...,정상결제횟수_sum,정상결제횟수_mean,정상결제횟수_std,카드코드_nunique,카드한도_mean,카드한도_std,카드현재잔액_mean,카드현재잔액_std,카드최고잔액_mean,카드최고잔액_std
0,58996294,7,1,2,11,5,3,1239.5,110000.0,80,...,26,6.500000,6.454972,2,107800.000000,NaN,341837.40,382976.993952,253341.750000,250922.387985
1,54988879,4,3,2,8,-1,5,1223.0,68000.0,112,...,38,12.666667,6.027714,2,74250.000000,11667.261890,19739.60,22504.881401,36681.666667,14667.393509
2,58984937,5,1,2,15,-1,4,1296.5,130000.0,86,...,79,15.800000,13.386560,2,16500.000000,NaN,29227.68,62191.709155,50258.600000,90255.710081
3,58987530,5,1,2,15,5,3,1304.0,146000.0,90,...,149,14.900000,15.444884,2,44805.514286,46327.898604,2053.68,4547.761408,37493.888889,23725.174038
4,59003965,4,2,2,8,9,4,0.0,76000.0,113,...,44,14.666667,11.239810,1,89100.000000,32668.333291,161.20,288.610187,19747.333333,13688.020030

In [ ]:
# 테스트 데이터도 동일한 방식으로 피쳐 추가
tmp = test_payment.groupby("고객ID").agg(agg_dict) # 동일한 방식으로 집계
tmp.columns = tmp.columns.droplevel() # 기본으로 0레벨 컬럼 제거해서 반환
tmp = tmp.reset_index()  # 고객ID 컬럼데이터로 만들기
test_ft = pd.merge(test_ft,tmp,how="left",on="고객ID")
test_ft.head()

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,...,정상결제횟수_sum,정상결제횟수_mean,정상결제횟수_std,카드코드_nunique,카드한도_mean,카드한도_std,카드현재잔액_mean,카드현재잔액_std,카드최고잔액_mean,카드최고잔액_std
0,58991594,7,3,1,11,5,5,1365.5,152000.0,84,...,117,16.714286,13.816829,4,120450.000000,145451.864890,237269.485714,388585.126964,250155.428571,391407.849007
1,54983822,5,3,2,15,5,4,0.0,94000.0,113,...,110,22.000000,7.000000,2,57200.000000,NaN,2450.640000,5487.179630,36809.600000,12823.881737
2,54984131,5,3,2,15,5,5,1244.0,57000.0,95,...,115,19.166667,8.704405,2,66366.666667,16838.745005,39169.000000,30712.634008,48969.666667,11405.139625
3,58994981,7,2,2,11,5,3,0.0,72000.0,109,...,30,15.000000,5.656854,1,NaN,NaN,19324.800000,27329.394250,48771.000000,54119.124605
4,59004856,4,2,2,8,5,3,0.0,99000.0,90,...,33,16.500000,13.435029,1,82500.000000,NaN,19231.800000,27369.275073,23714.500000,27969.608730

## 결측치를 처리하는 경우

- 결측치 확인

In [ ]:
train_ft.isnull().sum()

고객ID              0
범주1               0
범주2               0
범주3               0
범주4               0
범주5               0
범주6               0
수치1               0
수치2               0
수치3               0
수치4               0
수치5               0
수치1_mean          0
연체횟수유형1_sum       0
변제횟수              0
연체횟수유형2_sum       0
연체횟수유형3_sum       0
총연체일수_sum         0
정상결제횟수_sum        0
정상결제횟수_mean       0
정상결제횟수_std       35
카드코드_nunique      0
카드한도_mean       134
카드한도_std        421
카드현재잔액_mean       0
카드현재잔액_std       35
카드최고잔액_mean       0
카드최고잔액_std       36
dtype: int64

In [ ]:
test_ft.isnull().sum()

고객ID              0
범주1               0
범주2               0
범주3               0
범주4               0
범주5               0
범주6               0
수치1               0
수치2               0
수치3               0
수치4               0
수치5               0
수치1_mean          0
연체횟수유형1_sum       0
변제횟수              0
연체횟수유형2_sum       0
연체횟수유형3_sum       0
총연체일수_sum         0
정상결제횟수_sum        0
정상결제횟수_mean       0
정상결제횟수_std       12
카드코드_nunique      0
카드한도_mean        46
카드한도_std        169
카드현재잔액_mean       0
카드현재잔액_std       12
카드최고잔액_mean       0
카드최고잔액_std       13
dtype: int64

In [ ]:
cols = ["정상결제횟수_std","카드한도_mean","카드한도_std","카드현재잔액_std","카드최고잔액_std"] # 결측치가 있는 컬럼

### Data leakage 발생 예시

- 학습데이터와 테스트데이터를 합쳐서 통계치를 구해 결측치를 처리할 경우 Data leakage 이다.

In [ ]:
df = pd.concat([train_ft,test_ft]).reset_index(drop=True)
mean_series = df[cols].mean() # 컬럼별 평균 값이 시리즈 형태로 반환
df[cols] = df[cols].fillna(mean_series)
df.isnull().sum().sum()

0

- 테스트 데이터의 통계치를 구해 결측치를 처리할 경우 Data leakage 이다.

In [ ]:
mean_series = test_ft[cols].mean() # 컬럼별 평균 값이 시리즈 형태로 반환
test_ft[cols].fillna(mean_series)

     정상결제횟수_std      카드한도_mean       카드한도_std     카드현재잔액_std     카드최고잔액_std
0     13.816829  120450.000000  145451.864890  388585.126964  391407.849007
1      7.000000   57200.000000   49620.366749    5487.179630   12823.881737
2      8.704405   66366.666667   16838.745005   30712.634008   11405.139625
3      5.656854   81879.391782   49620.366749   27329.394250   54119.124605
4     13.435029   82500.000000   49620.366749   27369.275073   27969.608730
..          ...            ...            ...            ...            ...
333    4.349329   81879.391782   49620.366749  498550.920926  394427.443800
334   10.179302   81879.391782   49620.366749   12920.364138   26212.971881
335    8.276473   81879.391782   49620.366749  256848.631635  209631.629167
336   10.878113   82500.000000       0.000000     714.121334  200504.087986
337   14.139016  138325.000000  157645.453999  502593.507037  922430.833196

[338 rows x 5 columns]

### Data leakage 해결 방안
- 테스트데이터에 결측치를 처리할 때는 특정 상수값으로 처리하거나 학습데이터에서 구한 통계치로 결측치를 처리하면 된다.

In [ ]:
fill_value = 0
test_ft[cols].fillna(fill_value)

     정상결제횟수_std      카드한도_mean       카드한도_std     카드현재잔액_std     카드최고잔액_std
0     13.816829  120450.000000  145451.864890  388585.126964  391407.849007
1      7.000000   57200.000000       0.000000    5487.179630   12823.881737
2      8.704405   66366.666667   16838.745005   30712.634008   11405.139625
3      5.656854       0.000000       0.000000   27329.394250   54119.124605
4     13.435029   82500.000000       0.000000   27369.275073   27969.608730
..          ...            ...            ...            ...            ...
333    4.349329       0.000000       0.000000  498550.920926  394427.443800
334   10.179302       0.000000       0.000000   12920.364138   26212.971881
335    8.276473       0.000000       0.000000  256848.631635  209631.629167
336   10.878113   82500.000000       0.000000     714.121334  200504.087986
337   14.139016  138325.000000  157645.453999  502593.507037  922430.833196

[338 rows x 5 columns]

In [ ]:
mean_series = train_ft[cols].mean() # 컬럼별 평균 값이 시리즈 형태로 반환
mean_series

정상결제횟수_std        10.293741
카드한도_mean      81664.146523
카드한도_std       47539.969728
카드현재잔액_std    201296.634689
카드최고잔액_std    245571.641071
dtype: float64

In [ ]:
train_ft[cols] = train_ft[cols].fillna(mean_series)
test_ft[cols] = test_ft[cols].fillna(mean_series)
train_ft.isnull().sum().sum(), test_ft.isnull().sum().sum()

(0, 0)

## 범주형 피처를 인코딩 하는 경우

In [ ]:
cols = [ col for col in train_ft.columns if col.startswith("범주") ]
cols

['범주1', '범주2', '범주3', '범주4', '범주5', '범주6']

### Data leakage 발생 예시

- 원핫 인코딩을 할 때 테스트 데이터에 대하여 fit 을 하는 경우 Data leakage 이다.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
tmp = pd.DataFrame(
    enc.fit_transform(test_ft[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
pd.concat([test_ft, tmp], axis=1)

,고객ID,범주1,범주2,범주3,범주4,범주5,범주6,수치1,수치2,수치3,...,범주5_4,범주5_5,범주5_7,범주5_8,범주5_9,범주5_10,범주6_1,범주6_3,범주6_4,범주6_5
0,58991594,7,3,1,11,5,5,1365.5,152000.0,84,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,54983822,5,3,2,15,5,4,0.0,94000.0,113,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,54984131,5,3,2,15,5,5,1244.0,57000.0,95,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,58994981,7,2,2,11,5,3,0.0,72000.0,109,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,59004856,4,2,2,8,5,3,0.0,99000.0,90,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,58992009,7,3,2,11,9,3,1290.5,273000.0,113,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
334,58993131,7,2,2,11,5,5,0.0,120000.0,101,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
335,58993847,7,3,2,11,9,4,1262.0,172000.0,112,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
336,58995703,7,3,2,11,9,5,0.0,75000.0,100,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
337,54989304,4,3,2,8,9,5,1238.0,125000.0,85,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

### Data leakage 해결 방안
- 테스트 데이터에는 `transform` 만 해야한다. `fit` 하면 안된다.
- 모르는 데이터라고 가정한 테스트 데이터에 학습 데이터에는 없는 새로운 범주가 나왔을 경우 무시하기 위해 원핫 인코더에 `handle_unknown='ignore'` 인수를 주는 것이다.

In [ ]:
enc = OneHotEncoder(handle_unknown='ignore')
# 학습데이터
tmp = pd.DataFrame(
    enc.fit_transform(train_ft[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
train_ft = pd.concat([train_ft, tmp], axis=1)

# 테스트 데이터
tmp = pd.DataFrame(
    enc.transform(test_ft[cols]).toarray(), # transform만 해야한다.
    columns = enc.get_feature_names_out()
)
test_ft = pd.concat([test_ft, tmp], axis=1)

train_ft.shape , test_ft.shape

((787, 64), (338, 64))

- 기존 범주형 컬럼 및 고객ID 컬럼 제거

In [ ]:
cols.append("고객ID")
cols

['범주1', '범주2', '범주3', '범주4', '범주5', '범주6', '고객ID']

In [ ]:
train_ft = train_ft.drop(columns=cols)
test_ft = test_ft.drop(columns=cols)

train_ft.shape, test_ft.shape

((787, 57), (338, 57))

In [ ]:
train_ft.isnull().sum().sum() , test_ft.isnull().sum().sum()

(0, 0)

## 스케일링을 하는 경우

### Data leakage 발생 예시
- 학습데이터와 테스트데이터를 합쳐서 `fit` 하여 스케일링을 하는 경우 Data leakage 이다.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
df = pd.concat([train_ft,test_ft]).reset_index(drop=True)

scaler = MinMaxScaler()
scaler.fit_transform(df)

array([[0.8369345 , 0.08016878, 0.31372549, ..., 1.        , 0.        ,
        0.        ],
       [0.82579338, 0.04472574, 0.94117647, ..., 0.        , 0.        ,
        1.        ],
       [0.87542201, 0.09704641, 0.43137255, ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.85212694, 0.13248945, 0.94117647, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.05063291, 0.70588235, ..., 0.        , 0.        ,
        1.        ],
       [0.83592167, 0.092827  , 0.41176471, ..., 0.        , 0.        ,
        1.        ]])

- 테스트데이터에 대하여 `fit` 하여 스케일링을 하는 경우 Data leakage 이다.

In [ ]:
scaler = MinMaxScaler()
scaler.fit_transform(test_ft)

array([[0.92954391, 0.26637555, 0.39215686, ..., 0.        , 0.        ,
        1.        ],
       [0.        , 0.13973799, 0.96078431, ..., 0.        , 1.        ,
        0.        ],
       [0.84683458, 0.05895197, 0.60784314, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.85908781, 0.31004367, 0.94117647, ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.09825328, 0.70588235, ..., 0.        , 0.        ,
        1.        ],
       [0.84275017, 0.20742358, 0.41176471, ..., 0.        , 0.        ,
        1.        ]])

### Data leakage 해결 방안
- 테스트 데이터에는 `transform` 만 해야한다. `fit` 하면 안된다.

In [ ]:
scaler = MinMaxScaler()

# 학습데이터
train_ft = pd.DataFrame(
    scaler.fit_transform(train_ft),
    columns = train_ft.columns
)
train_ft.head()

,수치1,수치2,수치3,수치4,수치5,수치1_mean,연체횟수유형1_sum,변제횟수,연체횟수유형2_sum,연체횟수유형3_sum,...,범주5_5,범주5_7,범주5_8,범주5_9,범주5_10,범주6_1,범주6_2,범주6_3,범주6_4,범주6_5
0,0.836935,0.080169,0.313725,0.000108,0.000000,0.824824,0.000000,0.063830,0.000000,0.000000,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.825793,0.044726,0.941176,0.474544,0.268976,0.746379,0.000000,0.042553,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.875422,0.097046,0.431373,0.000031,0.227102,0.828295,0.000000,0.085106,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.880486,0.110549,0.509804,0.491481,0.000000,0.828295,0.014706,0.191489,0.043478,0.019608,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.000000,0.051477,0.960784,0.000154,0.227527,0.746379,0.000000,0.042553,0.000000,0.000000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
# 테스트 데이터
test_ft = pd.DataFrame(
    scaler.transform(test_ft),
    columns = test_ft.columns
)
test_ft.head()

,수치1,수치2,수치3,수치4,수치5,수치1_mean,연체횟수유형1_sum,변제횟수,연체횟수유형2_sum,연체횟수유형3_sum,...,범주5_5,범주5_7,범주5_8,범주5_9,범주5_10,범주6_1,범주6_2,범주6_3,범주6_4,범주6_5
0,0.922012,0.115612,0.392157,0.000010,0.248916,0.824824,0.000000,0.127660,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.000000,0.066667,0.960784,0.000097,0.278448,0.828295,0.014706,0.085106,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.839973,0.035443,0.607843,0.154727,0.248916,0.828295,0.000000,0.106383,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.000000,0.048101,0.882353,0.000032,0.243538,0.824824,0.000000,0.021277,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.000000,0.070886,0.509804,0.000061,0.270397,0.746379,0.000000,0.021277,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

# Data leakage로 인한 모델의 과대 평가 예시

- 타이타닉 생존자 데이터셋 다운로드 받아 구글드라이브에 올리기
    - 학습세트: https://drive.google.com/file/d/17DUdpAGVIPJ5_Cghku38YG5ugN6-SiNX/view?usp=sharing
    - 평가세트: https://drive.google.com/file/d/1ZhrzzI81mN_rFWXw68eO2a2NQ8vg8IlZ/view?usp=sharing
    - 평가세트 정답: https://drive.google.com/file/d/1kBJwGeAI1y81-gL8AAVVs4ealPHTcNNS/view?usp=sharing

- 시드값

In [ ]:
SEED = 42

- 데이터 불러오기

In [ ]:
train = pd.read_csv(f"{DATA_PATH}titanic_train.csv") # 학습데이터
test = pd.read_csv(f"{DATA_PATH}titanic_test.csv") # 테스트 데이터
test_target = pd.read_csv(f"{DATA_PATH}titanic_test_target.csv") # 테스트데이터 정답값
train.shape , test.shape , test_target.shape

((916, 12), (393, 11), (393, 2))

- 결측치 확인하기

In [ ]:
train.isnull().sum()

passengerid      0
survived         0
pclass           0
name             0
gender           0
age            180
sibsp            0
parch            0
ticket           0
fare             0
cabin          706
embarked         0
dtype: int64

In [ ]:
test.isnull().sum()

passengerid      0
pclass           0
name             0
gender           0
age             83
sibsp            0
parch            0
ticket           0
fare             1
cabin          308
embarked         2
dtype: int64

- 학습 데이터에서 얻은 통계량을 이용하여 결측치를 채워야한다.

In [ ]:
age_mean = train["age"].mean() # 평균
fare_median = train["fare"].median() # 중앙값
cabin_unk = "UNK" # 새로운 범주
embarked_mode = train["embarked"].mode()[0] # 최빈값
age_mean , fare_median ,cabin_unk , embarked_mode

(29.904891304347824, 14.5, 'UNK', 'S')

- 학습데이터 결측치 처리

In [ ]:
train["age"] = train["age"].fillna(age_mean)
train["cabin"] = train["cabin"].fillna(cabin_unk)

- 테스트데이터 결측치 처리

In [ ]:
test["age"] = test["age"].fillna(age_mean)
test["fare"] = test["fare"].fillna(fare_median)
test["cabin"] = test["cabin"].fillna(cabin_unk)
test["embarked"] = test["embarked"].fillna(embarked_mode)

In [ ]:
train.isnull().sum().sum() , test.isnull().sum().sum()

(0, 0)

- 특성으로 사용할 변수 추가하기

In [ ]:
cols = ["age","sibsp","parch","fare","pclass","gender","embarked","cabin"]
train_ft = train[cols].copy()
test_ft = test[cols].copy() # 테스트 데이터
train_ft.shape, test_ft.shape

((916, 8), (393, 8))

- 범주형 변수 원핫인코딩하여 특성으로 추가하기

In [ ]:
cols = ['gender','embarked']
enc = OneHotEncoder(handle_unknown = 'ignore') # 모르는 범주가 있을 경우 무시
enc.fit(train_ft[cols])

OneHotEncoder(handle_unknown='ignore')

In [ ]:
# 학습 데이터
tmp = pd.DataFrame(
    enc.transform(train_ft[cols]).toarray(), # ndarray
    columns = enc.get_feature_names_out() # 컬럼명
)
train_ft = pd.concat([train_ft,tmp],axis=1)
train_ft.head()

,age,sibsp,parch,fare,pclass,gender,embarked,cabin,gender_female,gender_male,embarked_C,embarked_Q,embarked_S
0,71.0,0,0,49.5042,1,male,C,UNK,0.0,1.0,1.0,0.0,0.0
1,34.0,0,0,8.0500,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0
2,29.0,3,1,22.0250,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0
3,18.0,1,1,13.0000,2,female,S,UNK,1.0,0.0,0.0,0.0,1.0
4,48.0,0,0,26.5500,1,male,S,E12,0.0,1.0,0.0,0.0,1.0

In [ ]:
# 테스트 데이터
tmp = pd.DataFrame(
    enc.transform(test_ft[cols]).toarray(),
    columns = enc.get_feature_names_out()
)
test_ft = pd.concat([test_ft,tmp],axis=1)
test_ft.head()

,age,sibsp,parch,fare,pclass,gender,embarked,cabin,gender_female,gender_male,embarked_C,embarked_Q,embarked_S
0,62.000000,0,0,26.5500,1,male,S,C87,0.0,1.0,0.0,0.0,1.0
1,28.000000,0,0,47.1000,1,male,S,UNK,0.0,1.0,0.0,0.0,1.0
2,24.000000,0,0,9.5000,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0
3,29.904891,0,0,7.7333,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0
4,18.500000,0,0,7.2833,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0

## cabin 별 fare와 age의 평균값을 피처로 추가

In [ ]:
agg_dict = {"fare": "mean","age": "mean"}
tmp = train.groupby("cabin").agg(agg_dict).add_suffix("_cabin_mean").reset_index()
train_ft = pd.merge(train_ft,tmp,how="left",on="cabin")
train_ft.head()

,age,sibsp,parch,fare,pclass,gender,embarked,cabin,gender_female,gender_male,embarked_C,embarked_Q,embarked_S,fare_cabin_mean,age_cabin_mean
0,71.0,0,0,49.5042,1,male,C,UNK,0.0,1.0,1.0,0.0,0.0,20.059507,28.038848
1,34.0,0,0,8.0500,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0,20.059507,28.038848
2,29.0,3,1,22.0250,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0,20.059507,28.038848
3,18.0,1,1,13.0000,2,female,S,UNK,1.0,0.0,0.0,0.0,1.0,20.059507,28.038848
4,48.0,0,0,26.5500,1,male,S,E12,0.0,1.0,0.0,0.0,1.0,26.550000,48.000000

### Data leakage가 아닌 경우의 테스트 셋

In [ ]:
test_ft = pd.merge(test_ft,tmp,how="left",on="cabin")
test_ft.head()

,age,sibsp,parch,fare,pclass,gender,embarked,cabin,gender_female,gender_male,embarked_C,embarked_Q,embarked_S,fare_cabin_mean,age_cabin_mean
0,62.000000,0,0,26.5500,1,male,S,C87,0.0,1.0,0.0,0.0,1.0,NaN,NaN
1,28.000000,0,0,47.1000,1,male,S,UNK,0.0,1.0,0.0,0.0,1.0,20.059507,28.038848
2,24.000000,0,0,9.5000,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0,20.059507,28.038848
3,29.904891,0,0,7.7333,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0,20.059507,28.038848
4,18.500000,0,0,7.2833,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0,20.059507,28.038848

### Data leakage에 해당하는 테스트 셋

- 위에서 추가한 피처 제외

In [ ]:
test_ft.iloc[:,:-2].head()

,age,sibsp,parch,fare,pclass,gender,embarked,cabin,gender_female,gender_male,embarked_C,embarked_Q,embarked_S
0,62.000000,0,0,26.5500,1,male,S,C87,0.0,1.0,0.0,0.0,1.0
1,28.000000,0,0,47.1000,1,male,S,UNK,0.0,1.0,0.0,0.0,1.0
2,24.000000,0,0,9.5000,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0
3,29.904891,0,0,7.7333,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0
4,18.500000,0,0,7.2833,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0

- 테스트 데이터를 집계하여 피처를 추가해서 Data leakage 문제 발생

In [ ]:
tmp = test.groupby("cabin").agg(agg_dict).add_suffix("_cabin_mean").reset_index()
test_ft_leakage = pd.merge(test_ft.iloc[:,:-2],tmp,how="left",on="cabin")
test_ft_leakage.head()

,age,sibsp,parch,fare,pclass,gender,embarked,cabin,gender_female,gender_male,embarked_C,embarked_Q,embarked_S,fare_cabin_mean,age_cabin_mean
0,62.000000,0,0,26.5500,1,male,S,C87,0.0,1.0,0.0,0.0,1.0,26.550000,62.000000
1,28.000000,0,0,47.1000,1,male,S,UNK,0.0,1.0,0.0,0.0,1.0,16.993248,27.904212
2,24.000000,0,0,9.5000,3,male,S,UNK,0.0,1.0,0.0,0.0,1.0,16.993248,27.904212
3,29.904891,0,0,7.7333,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0,16.993248,27.904212
4,18.500000,0,0,7.2833,3,female,Q,UNK,1.0,0.0,0.0,1.0,0.0,16.993248,27.904212

- 파생변수 생성과정에서 생긴 결측치 처리하기

In [ ]:
train_ft.isnull().sum().sum(), test_ft.isnull().sum().sum(), test_ft_leakage.isnull().sum().sum()

(0, 94, 0)

In [ ]:
test_ft.isnull().sum()

age                 0
sibsp               0
parch               0
fare                0
pclass              0
gender              0
embarked            0
cabin               0
gender_female       0
gender_male         0
embarked_C          0
embarked_Q          0
embarked_S          0
fare_cabin_mean    47
age_cabin_mean     47
dtype: int64

In [ ]:
# 학습데이터에서 얻은 통계치로 결측치를 처리
cols = ["fare_cabin_mean","age_cabin_mean"]
median_series = train_ft[cols].median()
test_ft[cols] = test_ft[cols].fillna(median_series)
test_ft.isnull().sum().sum()

0

- 문자열 데이터 제거

In [ ]:
cols = ["gender","embarked","cabin"]
train_ft = train_ft.drop(columns=cols)
test_ft = test_ft.drop(columns=cols)
test_ft_leakage = test_ft_leakage.drop(columns=cols) # data leakage 데이터

- 정답 데이터

In [ ]:
target = train["survived"]
target

0      0
1      0
2      0
3      1
4      1
      ..
911    1
912    0
913    0
914    0
915    0
Name: survived, Length: 916, dtype: int64

- 모델 교차검증 점수 확인하기

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMClassifier
from sklearn.model_selection import KFold

cv = KFold(n_splits=10,shuffle=True, random_state=SEED)
model = LGBMClassifier(random_state=SEED)

/usr/local/lib/python3.11/dist-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

In [ ]:
scores = cross_val_score(model,train_ft,target,cv = cv ,scoring='roc_auc',n_jobs = -1)
np.mean(scores)

0.8985310928916679

- 모델 학습

In [ ]:
model.fit(train_ft,target)

[LightGBM] [Info] Number of positive: 346, number of negative: 570
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000230 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 346
[LightGBM] [Info] Number of data points in the train set: 916, number of used features: 12
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.377729 -> initscore=-0.499198
[LightGBM] [Info] Start training from score -0.499198
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(random_state=42)

## Data leakage에 아닌 테스트 데이터 예측 및 평가

In [ ]:
from sklearn.metrics import roc_auc_score
y_test = test_target["survived"] # 테스트셋 y값
pred = model.predict_proba(test_ft)[:,1] # 예측
roc_auc_score(y_test,pred) # AUC 평가

0.8751241036955323

## Data leakage에 해당하는 테스트 데이터 예측 및 평가
- 모델이 과대평가 된다.

In [ ]:
y_test = test_target["survived"] # 테스트셋 y값
pred = model.predict_proba(test_ft_leakage)[:,1] # 예측
roc_auc_score(y_test,pred) # AUC 평가

0.883342526199669